# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'processwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProcessWindow(object):
    def setupUi(self, ProcessWindow):
        ProcessWindow.setObjectName("ProcessWindow")
        ProcessWindow.resize(429, 104)
        ProcessWindow.setMinimumSize(QtCore.QSize(429, 104))
        ProcessWindow.setMaximumSize(QtCore.QSize(429, 104))
        self.progressBar = QtWidgets.QProgressBar(ProcessWindow)
        self.progressBar.setGeometry(QtCore.QRect(50, 40, 341, 23))
        self.progressBar.setProperty("value", 100)
        self.progressBar.setObjectName("progressBar")
        self.pushButton = QtWidgets.QPushButton(ProcessWindow)
        self.pushButton.setGeometry(QtCore.QRect(170, 70, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(ProcessWindow)
        self.label.setGeometry(QtCore.QRect(150, 10, 171, 16))
        self.label.setObjectName("label")

        self.retranslateUi(ProcessWindow)
        QtCore.QMetaObject.connectSlotsByName(ProcessWindow)

    def retranslateUi(self, ProcessWindow):
        _translate = QtCore.QCoreApplication.translate
        ProcessWindow.setWindowTitle(_translate("ProcessWindow", "进度条"))
        self.pushButton.setText(_translate("ProcessWindow", "取消"))
        self.label.setText(_translate("ProcessWindow", "正在处理文件夹中的文件..."))
