# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'videowindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VideoWindow(object):
    def setupUi(self, VideoWindow):
        VideoWindow.setObjectName("VideoWindow")
        VideoWindow.resize(989, 754)
        VideoWindow.setMinimumSize(QtCore.QSize(989, 754))
        VideoWindow.setMaximumSize(QtCore.QSize(989, 754))
        self.label_show_camera = QtWidgets.QLabel(VideoWindow)
        self.label_show_camera.setGeometry(QtCore.QRect(10, 20, 640, 360))
        self.label_show_camera.setMinimumSize(QtCore.QSize(640, 360))
        self.label_show_camera.setMaximumSize(QtCore.QSize(640, 360))
        self.label_show_camera.setStyleSheet("border:0.5px solid")
        self.label_show_camera.setText("")
        self.label_show_camera.setObjectName("label_show_camera")
        self.label_show_camera1 = QtWidgets.QLabel(VideoWindow)
        self.label_show_camera1.setGeometry(QtCore.QRect(10, 390, 640, 360))
        self.label_show_camera1.setMinimumSize(QtCore.QSize(640, 360))
        self.label_show_camera1.setMaximumSize(QtCore.QSize(640, 360))
        self.label_show_camera1.setStyleSheet("border:0.5px solid")
        self.label_show_camera1.setText("")
        self.label_show_camera1.setObjectName("label_show_camera1")
        self.open_video = QtWidgets.QPushButton(VideoWindow)
        self.open_video.setGeometry(QtCore.QRect(710, 140, 81, 31))
        self.open_video.setObjectName("open_video")
        self.line = QtWidgets.QFrame(VideoWindow)
        self.line.setGeometry(QtCore.QRect(5, 378, 981, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.btn1 = QtWidgets.QPushButton(VideoWindow)
        self.btn1.setGeometry(QtCore.QRect(710, 180, 81, 31))
        self.btn1.setObjectName("btn1")
        self.textBrowser = QtWidgets.QTextBrowser(VideoWindow)
        self.textBrowser.setGeometry(QtCore.QRect(670, 390, 315, 361))
        self.textBrowser.setObjectName("textBrowser")
        self.line_2 = QtWidgets.QFrame(VideoWindow)
        self.line_2.setGeometry(QtCore.QRect(650, 390, 20, 361))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")

        self.retranslateUi(VideoWindow)
        QtCore.QMetaObject.connectSlotsByName(VideoWindow)

    def retranslateUi(self, VideoWindow):
        _translate = QtCore.QCoreApplication.translate
        VideoWindow.setWindowTitle(_translate("VideoWindow", "视频检测"))
        self.open_video.setText(_translate("VideoWindow", "打开视频"))
        self.btn1.setText(_translate("VideoWindow", "检测视频"))
